#pragma config(Sensor, dgtl12,  clawSolenoid,   sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//the ports:
//2: left drive
//3: right drive
//4, 5, 6, 7: lift (4 and 6 flipped)
//dgtl 12: solenoid

void powerLift(int p) {
	motor[port5] = -p;
	motor[port6] = p;
	motor[port7] = -p;
	motor[port8] = p;
}

task driveControl() {
	int profile = 0;
	while(true){
		if(vexRT(Btn8U) == 1) {
			profile = 0;
		}
		else if (vexRT(Btn8D) == 1) {
			profile = 1;
		}
		if(profile == 0){
			motor[port2] = -1 * ( -1 * vexRT(Ch1) - vexRT(Ch3) );
			motor[port3] = -1 * (  -1 * vexRT(Ch1) + vexRT(Ch3) );
		}
		else if (profile == 1) {
			motor[port2] = vexRT(Ch3);
			motor[port3] = -1 * vexRT(Ch2);
		}
	}
}

//claw is hold-to-close.
task clawControl() {
	while(true) {
		if(vexRT(Btn7U) == 1) {
			SensorValue[clawSolenoid] = 1;
		}
		else {
			SensorValue[clawSolenoid]= 0;
		}
	}
}

task liftControl() {
	while(true){
		if(vexRT(Btn6U) == 1) {
			powerLift(127);
		}
		else if(vexRT(Btn6D) == 1) {
			powerLift(-127);
		}
		else {
			powerLift(0);
		}
	}
}

task rollerControl() {
	while(true) {
		if(vexRT(Btn7L) == 1) {
			motor[port9] = 127;
		}
		else if(vexRT(Btn7R) == 1) {
			motor[port9] = -127;
		}
		else{
			motor[port9] = 0;
		}
	}
}

task main()
{
	startTask(driveControl);
	startTask(clawControl);
	startTask(liftControl);
	startTask(rollerControl);
	while(true) {
		wait1Msec(10);
	}
}
